---
- name: tzdata-update
  command: /usr/sbin/tzdata-update
  notify: restart rsyslog

- name: restart rsyslog
  service: state=restarted name=rsyslog enabled=yes
  notify: restart crond

- name: restart crond
  service: state=restarted name=crond enabled=yes
