---
- name: glusterfs repo is installed
  template: 
    src=glusterfs-epel.repo.j2
    dest=/etc/yum.repos.d/glusterfs-epel.repo

- name: glusterfs client packages are present
  yum: 
    state=present
    name={{ item }}
    enablerepo=glusterfs-epel,glusterfs-noarch-epel
  with_items:
    - glusterfs
    - glusterfs-fuse

- name: the fuse module is present
  modprobe: 
    name=fuse
    state=present
