---
- name: libselinux-python is installed
  yum: state=present name=libselinux-python

- name: timezone is set correctly in clock file
  template: src=clock.j2 dest=/etc/sysconfig/clock
  notify: tzdata-update

- name: epel.repo is installed
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo

- name: epel gpg key is present
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6

- name: ius.repo is installed
  template: src=etc_yum.repos.d_ius.repo.j2 dest=/etc/yum.repos.d/ius.repo

- name: ius gpg key is present
  copy: src=etc_pki_rpm-gpg_IUS-COMMUNITY-GPG-KEY dest=/etc/pki/rpm-gpg/IUS-COMMUNITY-GPG-KEY
