---
- name: libselinux-python is present
  yum: 
    state=present
    name=libselinux-python

- name: disable iptables
  service: 
    state=stopped
    name=iptables
    enabled=no

- name: timezone is set correctly in clock file
  template: 
    src=clock.j2
    dest=/etc/sysconfig/clock
  notify: tzdata-update

# Rackspace managed dedicated servers use the epel-release package
- name: epel-release is installed on bare metal
  yum: 
    state=present
    name=epel-release
  when: ansible_form_factor == "Rack Mount Chassis"

# Install epel via templates on all other servers
- name: Check if epel repo is present
  shell: yum repolist | grep -i epel
  register: epel_check
  ignore_errors: yes
  when: ansible_form_factor != "Rack Mount Chassis" and ansible_os_family == "RedHat" 

- name: epel.repo is present
  template: 
    src=epel.repo.j2
    dest=/etc/yum.repos.d/epel.repo
  when: ansible_form_factor != "Rack Mount Chassis" and epel_check.rc == 1

- name: epel gpg key is present
  copy: 
    src=RPM-GPG-KEY-EPEL-6
    dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
  when: ansible_form_factor != "Rack Mount Chassis" and epel_check.rc == 1
