---
- name: libselinux-python is present
  yum: state=present name=libselinux-python

- name: turn iptables off :O
  service: state=stopped name=iptables enabled=no

- name: timezone is set correctly in clock file
  template: src=clock.j2 dest=/etc/sysconfig/clock
  notify: tzdata-update

# Rackspace dedicated servers can use epel-release package
- name: epel-release is installed
  yum: state=present name=epel-release
  when: ansible_form_factor == "Rack Mount Chassis"

# Install the package for all other boxes
- name: epel.repo is present
  template: src=epel.repo.j2 dest=/etc/yum.repos.d/epel.repo
  when: ansible_form_factor != "Rack Mount Chassis"

- name: epel gpg key is present
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
  when: ansible_form_factor != "Rack Mount Chassis"
