---
- name: Check if httpd package is present
  shell: rpm -q httpd
  register: httpd_check
  ignore_errors: yes
  when: ansible_os_family == "RedHat"

- name: httpd is stopped and disabled 
  service: 
    state=stopped
    name=httpd
    enabled=no
  when: httpd_check.rc == 0

- name: nginx.repo is installed
  template: 
    src=nginx.repo.j2
    dest=/etc/yum.repos.d/nginx.repo

- name: nginx is present
  yum: 
    state=present
    name=nginx
  notify: restart nginx

- name: default.conf is absent
  file: 
    state=absent
    dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: ssl certificate is present
  copy: 
    src=localhost.crt
    dest=/etc/pki/tls/certs/localhost.crt

- name: ssl private key is present
  copy: 
    src=localhost.key
    mode=0600
    dest=/etc/pki/tls/private/localhost.key

- name: nginx is configured
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: nginx vhost is configured
  template: 
    src=vhost.conf.j2
    dest=/etc/nginx/conf.d/{{ vhost_domain }}.conf
  notify: restart nginx

- name: ulimit is adjusted for nginx
  template:
    src=limits_nginx.conf.j2
    dest=/etc/security/limits.d/nginx.conf
  notify: restart nginx

- name: document root exists
  file: 
    state=directory
    path={{ document_root }}
    owner={{ vhost_user_uid }}
    group={{ vhost_user_uid }}
    mode=0775

- name: index placeholder
  template: 
    src=httpdocs_index.php.j2
    dest={{ document_root }}/index.php

- name: vhost user exists
  user: 
    state=present
    name={{ vhost_user }}
    uid={{ vhost_user_uid }}
    groups={{ webserver }}
    shell=/sbin/nologin
    comment={{ vhost_domain }}
    home={{ document_root }}/
    non_unique=yes

- name: nginx is started and enabled on boot
  service: 
    state=started
    name=nginx
    enabled=yes
