---
- name: Check if httpd package is present
  shell: rpm -q httpd
  register: httpd_check
  ignore_errors: yes
  when: ansible_os_family == "RedHat"

- name: httpd is stopped and disabled 
  service: 
    state=stopped
    name=httpd
    enabled=no
  when: httpd_check.rc == 0

- name: varnish repo is installed
  template: 
    src=varnish.repo.j2
    dest=/etc/yum.repos.d/varnish.repo

- name: varnish is installed
  yum: 
    state=present
    name=varnish
    enablerepo=varnish-3.0

- name: varnish is configured
  template: 
    src={{ item.src }}
    dest={{ item.dest }}
  with_items:
    - { src: 'etc_sysconfig_varnish.j2', dest: '/etc/sysconfig/varnish' }
    - { src: 'etc_varnish_default.vcl.j2', dest: '/etc/varnish/default.vcl' }
  notify: restart varnish

- name: varnish is started and enabled on boot
  service: 
    state=started
    name=varnish
    enabled=yes
