---
- name: php-fpm package is present
  yum: 
    state=present
    name={{ php_version }}-fpm

- name: php-fpm is configured
  template: 
    src={{ item.src }}
    dest={{ item.dest }}
    validate='php-fpm -ty %s'
  with_items:
    - { src: 'etc_php-fpm.conf.j2', dest: '/etc/php-fpm.conf' }
    - { src: 'etc_php-fpm.d_vhost.conf.j2', dest: '/etc/php-fpm.d/{{ vhost_domain }}.conf' }
  notify: restart php-fpm

- name: default php-fpm pool placeholder is in place
  template:
    src=etc_php-fpm.d_www.conf.j2
    dest=/etc/php-fpm.d/www.conf
  notify: restart php-fpm

- name: php-fpm is started and enabled on boot
  service: 
    state=started
    name=php-fpm 
    enabled=yes
