---
- name: web root directory is present 
  copy: src=files/downloads/ dest=/home/downloads/ owner=downloads group=downloads mode=0775

- name: web root completed directory
  file: path=/home/downloads/complete state=directory mode=2775 owner=downloads group=downloads

- name: nginx is installed at the latest version
  yum: name=nginx state=present
  notify: restart nginx

- name: nginx user is in the downloads group
  user: name=nginx state=present append=yes groups=downloads

- name: nginx is started and enabled on boot
  service: name=nginx enabled=yes state=started

- name: default.conf is configured
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: nginx.conf is configured
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx