---
- name: MariaDB repo is installed
  template: src=MariaDB.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo

- name: MariaDB gpg key is installed
  copy: src=RPM-GPG-KEY-MariaDB dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-MariaDB

- name: MariaDB/MySQL packages are present
  yum: state=present name={{ item }}
  with_items:
    - MySQL-python
    - MariaDB-client
    - MariaDB-server

- name: /var/lib/mysqltmp/ exists
  file: state=directory path=/var/lib/mysqltmp/ owner=mysql group=mysql

- name: /var/log/mysql/ exists
  file: state=directory path=/var/log/mysql/ owner=mysql group=mysql

- name: /etc/my.cnf is configured
  template: src=etc_my.cnf.j2 dest=/etc/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- name: mariadb service is started and enabled
  service: state=started name=mysql enabled=yes

- name: root mysql user accounts exist
  mysql_user: state=present name=root host={{ item }} password={{ mysql_root_pw }}
  with_items:
    - "%"
    - 127.0.0.1
    - localhost

- name: root's mysql client is updated
  template: src=root_.my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600

- name: anonymous mysql users are absent
  mysql_user: state=absent name= host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - localhost

- name: superfluous root mysql users are absent
  mysql_user: state=absent name=root host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - ::1

- name: mysql test database is absent
  mysql_db: state=absent name=test
