---
# Global MySQL Defaults
mysql_root_pw: test666
max_allowed_packet: 67108864
max_connections: 200

# InnoDB Defaults
innodb_lock_wait_timeout: 1800
innodb_buffer_pool_size: 1G
innodb_log_file_size: 100M

# MyISAM Defaults

# Temp tables
tmp_table_size: 256M
max_heap_table_size: 64M
