---
- name: remi.repo is installed
  template: 
    src=remi.repo.j2
    dest=/etc/yum.repos.d/remi.repo

- name: remi gpg key is present
  copy: 
    src=RPM-GPG-KEY-remi
    dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-remi
