---
- hosts: dbservers
  sudo: yes
  roles: 
    # database: mariadb, percona, or mysql55
    - mariadb
    #  - memcached  

- hosts: webservers
  sudo: yes
  roles:
    - redis
    # webserver: nginx or apache
    - nginx
    - php-5.4
    - php-fpm
    - magento
