# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # https://vagrantcloud.com/chef/centos-6.5
    config.vm.box = "chef/centos-6.5"

    config.vm.define "db01" do |db01|
        db01.vm.hostname = "db01"
        db01.vm.network "private_network", ip: "192.168.150.10"
    end

    config.vm.define "web01" do |web01|
        web01.vm.hostname = "web01"
        web01.vm.network "private_network", ip: "192.168.150.5"

    config.vm.provision "ansible" do |magento|
        magento.playbook = "playbook.yml"
        magento.groups = {
        "webservers" => ["web01"],
        "dbservers" => ["db01"],
        "all_groups:children" => ["webservers", "dbservers"]
        }
        magento.limit = 'all'
    end
  
    end
 
 end
