---
- name: rpmfusion-nonfree-updates.repo is installed
  copy: src=rpmfusion-nonfree-updates.repo dest=/etc/yum.repos.d/rpmfusion-nonfree-updates.repo

- name: rpmfusion GPG key is installed
  copy: src=RPM-GPG-KEY-rpmfusion-nonfree-el-6 dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-rpmfusion-nonfree-el-6

- name: unrar is installed
  yum: name=unrar state=present enablerepo=rpmfusion-nonfree-updates

- name: sabnzbd.repo is installed
  copy: src=sabnzbd.repo dest=/etc/yum.repos.d/sabnzbd.repo

- name: SABnzbd package is installed to latest version
  yum: name=SABnzbd state=latest
  notify: restart SABnzbd

- name: /etc/sysconfig/SABnzbd is configured
  template: src=SABnzbd.j2 dest=/etc/sysconfig/SABnzbd
  notify: restart SABnzbd

- name: sabnzbd user exists
  user: name={{ sabuser }} state=present shell=/sbin/nologin system=yes

- name: sabuser is in the downloads group
  user: name={{ sabuser }} state=present append=yes groups=downloads

- name: hidden directory exists
  file: dest=/home/{{ sabuser }}/.sabnzbd state=directory owner={{ sabuser }} group={{ sabuser }}

- name: sabnzbd.ini is configured
  template: src=sabnzbd.ini.j2 dest=/home/{{ sabuser }}/.sabnzbd/sabnzbd.ini mode=0600 owner={{ sabuser }} group={{ sabuser }}
  notify: restart SABnzbd

- name: SABnzbd service is started
  service: name=SABnzbd enabled=yes state=started sleep=15