---
- name: check if mysql-server is installed...
  shell: rpm -q mysql-server
  register: mysql_installed
  ignore_errors: yes
  when: ansible_os_family == "RedHat"

- name: mysqld service is stopped
  service: 
    state=stopped
    name=mysqld
    enabled=no
  when: mysql_installed.rc == 0

- name: remove mysql rpms if installed
  shell: rpm -e mysql mysql-server --nodeps
  when: mysql_installed.rc == 0

- name: /etc/my.cnf is present
  template: 
    src=my.cnf.j2
    dest=/etc/my.cnf
    owner=root
    group=root
    mode=0644
  notify: restart mysql

- name: percona repo is installed
  template: 
    src=Percona.repo.j2
    dest=/etc/yum.repos.d/Percona.repo

- name: percona gpg key is installed
  copy: 
    src=RPM-GPG-KEY-percona
    dest=/etc/pki/rpm-gpg/RPM-GPG-KEY-percona

- name: percona packages are present
  yum: 
    state=present
    name={{ item }}
    enablerepo=percona
  with_items:
    - Percona-Server-shared-{{ percona_version }}
    - Percona-Server-client-{{ percona_version }}
    - Percona-Server-server-{{ percona_version }}
    - Percona-Server-shared-compat
    - MySQL-python

- name: mysql service is started and enabled
  service: 
    state=started
    name=mysql
    enabled=yes

- name: root mysql user accounts exist
  mysql_user:
    state=present
    name=root
    host={{ item }}
    password={{ mysql_root_pw }}
    priv=*.*:ALL,GRANT
  with_items:
    - "%"
    - 127.0.0.1
    - localhost

- name: root's mysql client is updated
  template: 
    src=root_.my.cnf.j2
    dest=/root/.my.cnf
    owner=root
    group=root
    mode=0600

- name: hardening | anonymous mysql users are absent
  mysql_user: 
    state=absent
    name=
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - localhost
  tags:
    - hardening

- name: hardening | superfluous root mysql users are absent
  mysql_user: 
    state=absent
    name=root
    host={{ item }}
  with_items:
    - "{{ ansible_hostname }}"
    - ::1
  tags:
    - hardening

- name: hardening | mysql test database is absent
  mysql_db: 
    state=absent
    name=test
  tags:
    - hardening
