---
- name: Install sabnzbd on RHEL 6 and derivatives 
  hosts: sabnzbd-node
  gather_facts: true
  # vagrant requires sudo
  sudo: yes
  remote_user: vagrant
  # remote_user: root
  roles:
    - sabnzbd
    - nginx
