# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    config.vm.define "catcora" do |catcora|
        catcora.vm.box = "chef/centos-6.5"
        catcora.vm.hostname = "catcora"
        catcora.vm.network "private_network", ip: "192.168.150.150"
    end

    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "site.yml"
        ansible.groups = {
        "sabnzbd-node" => ["catcora"],
        }
    end   

 end